Korolev feature cache (room)
AndreyKoroliov1981/Korolev_aston_course_project pull request #6
Opened 2023-03-22 07:20 UTC by AndreyKoroliov1981

Добавил кэширование в Room для всех экранов, наверняка есть недочеты, но старался сделать к первоначальному сроку.
Вроде все задачи по курсовому выполнены.
Буду готовиться к собеседованию и сделаю домашнее задание по сервисам.

2023-03-26 06:52 UTC, AleksGirev requested changes
кажется, ты не в полной мере использовал Dagger в проекте. В частности, при инициализации базы данных и классов ретрофита. 
Класс HistoryManager нарушает принцип единственной ответственности. Его нужно изменить или от него отказаться
Нейминг тоже можно в некоторых местах улучшить. Последним словом имени лучше писать имя, обозначающее этот класс. Repository, Service etc.
Плюс можешь почитать теорию по паттернам проектирования. Для чего они нужны, основные виды, почитать про реализацию самых популярных паттернов.

В остальном всё неплохо. Жду твой ПР с улучшениями и запиши, пожалуйста, демо приложения. Можешь сбросить в личку

2023-03-26 06:52 UTC, AleksGirev commented on app/src/main/java/com/example/rickandmorty/di/DataModule.kt
> +    fun provideHistoryRepository(context: Context): HistoryRepositoryCharacters {
тут не совсем понял. Название метода одно, возвращаемое значение второе, а внутри методов вызывается одна и та же строка HistoryManager(context=context)

2023-03-26 06:52 UTC, AleksGirev commented on data/src/main/java/com/example/data/repository/cache/HistoryRepositoryLocations.kt
> +interface HistoryRepositoryLocations {
LocationsHistoryRepository

2023-03-26 06:52 UTC, AleksGirev commented on data/src/main/java/com/example/data/database/HistoryManager.kt
> +class HistoryManager(context: Context) : HistoryRepositoryCharacters, HistoryRepositoryLocations,
этот класс нарушает принцип единственной ответственности. Он отвечает за создание экземпляров сущностей. Которые сам же потом использует внутри себя. Плюс в нем сосредоточены классы для сохранения истории 3 разных сущностей. это тоже можно разделить по отдельным dataSource и поместить locationDataSource в locationRepository, episodesDatasource в episodesRepository. И почему нельзя инициализацию всех этих сущностей вынести в даггеровские модули?

2023-03-26 06:52 UTC, AleksGirev commented on data/src/main/java/com/example/data/network/episodes/EpisodesRetrofitClient.kt
> +object EpisodesRetrofitClient {
почему инициализацию ретрофита нельзя вынести в даггеровский модуль? Зачем нам нужен этот object?

2023-03-26 06:52 UTC, AleksGirev commented on data/src/main/java/com/example/data/network/episodes/EpisodesCommon.kt
> +object EpisodesCommon {
ты вроде бы инициализацию этого сервиса сделал в даггеровском модуле через provides. Зачем нам тогда этот object?

2023-03-26 06:52 UTC, AleksGirev commented on data/src/main/java/com/example/data/repository/personage/LocationeMapper.kt
> +        return Locations(
в таких местах можно использовать скоуп-функцию with()

2023-03-26 13:01 UTC, AndreyKoroliov1981 commented on data/src/main/java/com/example/data/repository/cache/HistoryRepositoryLocations.kt
> +interface HistoryRepositoryLocations {
Переименовал

2023-03-26 17:56 UTC, AndreyKoroliov1981 commented on data/src/main/java/com/example/data/network/episodes/EpisodesCommon.kt
> +object EpisodesCommon {
Удалил этот object, сделал через даггер.

2023-03-26 17:56 UTC, AndreyKoroliov1981 commented on data/src/main/java/com/example/data/network/episodes/EpisodesRetrofitClient.kt
> +object EpisodesRetrofitClient {
Удалил этот object, сделал через даггер.

2023-03-26 20:17 UTC, AndreyKoroliov1981 commented on app/src/main/java/com/example/rickandmorty/di/DataModule.kt
> +    fun provideHistoryRepository(context: Context): HistoryRepositoryCharacters {
изменил структуру DI

2023-03-26 20:19 UTC, AndreyKoroliov1981 commented on data/src/main/java/com/example/data/database/HistoryManager.kt
> +class HistoryManager(context: Context) : HistoryRepositoryCharacters, HistoryRepositoryLocations,
Удалил данный класс

2023-03-28 07:35 UTC, AleksGirev approved these changes

2023-03-28 07:35 UTC, AleksGirev commented on app/src/main/java/com/example/rickandmorty/di/AppModule.kt
> +    fun provideCharactersUiMapper(): CharactersUiMapper {
изучи тему @Inject через конструктор

2023-03-28 07:36 UTC, AleksGirev approved these changes

2023-03-28 08:01 UTC, merged